### PR TITLE
Add support for GHC 8.8.1.

### PR DESCRIPTION
**Pull request by athas**
This addresses #33.

### CODE REVIEW

**Comment by newhoggy** [comment]
This PR fixes the problem for me.

**Comment by mrkkrp** [comment]
@vincenthz Is there anything that prevents this PR from merging?

**Comment by domenkozar** [comment]
Blocking https://github.com/haskell-servant/servant-auth/pull/154

**Comment by ocheron** [comment]
@vincenthz When possible it would be good to fix the `master` / `updates` split and release asn1-encoding & asn1-parse. Stackage Nightly recently switched to GHC 8.8.1 and packages like tls have been removed.

**Pull request merged**
